### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by danielcorin** [morganthrapp/pyACH#4]
If would be helpful if the documentation contained working examples.

`//` is not a valid comment in Python

The following line contains a malformed string since you use single quotes and also the string `Here's`
```
payment_file.batch_records[-1].entry_records[-1].add_addenda(addenda_type, 'Here's some additional information about the transaction')
```

**Comment by morganthrapp** [comment]
You are complete right, I'll fix that up later today. Thanks for pointing it out!

**Comment by morganthrapp** [comment]
@danielcorin I just pushed the latest copy of what I have on local, including documentation fixes. Let me know if you find any other issues.

**Comment by soggysec** [comment]
Is there a way to create an ACH Object from an existing file? I'd like to parse out information I care about using this library.

**Comment by morganthrapp** [comment]
Currently there is not, but that's a really interesting idea. I'd be
willing to try to implement that this weekend if I get a chance.
